name = "einthusan-tv-api"
main = "src/index.js"
compatibility_date = "2024-09-23"

[vars]
APP_URL = "https://einthusan.mainframe.website"

[[kv_namespaces]]
binding = "USER_DATA"
id = "3eb8029c035a47998fb25d97d161b837"
preview_id = "30acedfad88c4661a93415a3873eda27"

# Optional: npx wrangler secret put RESEND_API_KEY  (free tier at resend.com)

[dev]
port = 8787
